// Zoznam slovenských miest pre autocomplete trás
// ZVL (sídlo firmy) ako prvá položka, potom krajské mestá, potom abecedne
export const SLOVAK_CITIES: string[] = [
  // Sídlo firmy
  'ZVL',
  // Krajské mestá
  'Bratislava',
  'Košice',
  'Prešov',
  'Žilina',
  'Banská Bystrica',
  'Nitra',
  'Trnava',
  'Trenčín',
  // Ostatné mestá abecedne
  'Bánovce nad Bebravou',
  'Banská Štiavnica',
  'Bardejov',
  'Bojnice',
  'Brezno',
  'Brezová pod Bradlom',
  'Bytča',
  'Čadca',
  'Detva',
  'Dolný Kubín',
  'Dubnica nad Váhom',
  'Dunajská Streda',
  'Fiľakovo',
  'Galanta',
  'Gelnica',
  'Handlová',
  'Hlohovec',
  'Hnúšťa',
  'Holíč',
  'Humenné',
  'Hurbanovo',
  'Ilava',
  'Jelšava',
  'Kežmarok',
  'Kolárovo',
  'Komárno',
  'Košice-okolie',
  'Kremnica',
  'Krupina',
  'Kysucké Nové Mesto',
  'Leopoldov',
  'Levice',
  'Levoča',
  'Lipany',
  'Liptovský Mikuláš',
  'Lučenec',
  'Malacky',
  'Martin',
  'Medzilaborce',
  'Medzev',
  'Michalovce',
  'Modra',
  'Moldava nad Bodvou',
  'Modrý Kameň',
  'Myjava',
  'Námestovo',
  'Nitra-okolie',
  'Nová Baňa',
  'Nová Dubnica',
  'Nové Mesto nad Váhom',
  'Nové Zámky',
  'Partizánske',
  'Pezinok',
  'Piešťany',
  'Podolínec',
  'Poltár',
  'Poprad',
  'Považská Bystrica',
  'Prievidza',
  'Púchov',
  'Revúca',
  'Rimavská Sobota',
  'Rožňava',
  'Ružomberok',
  'Sabinov',
  'Šahy',
  'Šaľa',
  'Šamorín',
  'Sečovce',
  'Senec',
  'Senica',
  'Sereď',
  'Skalica',
  'Sládkovičovo',
  'Snina',
  'Sobrance',
  'Spišská Belá',
  'Spišská Nová Ves',
  'Spišská Stará Ves',
  'Spišské Podhradie',
  'Spišské Vlachy',
  'Stará Ľubovňa',
  'Stará Turá',
  'Stropkov',
  'Stupava',
  'Šurany',
  'Svätý Jur',
  'Svidník',
  'Šaštín-Stráže',
  'Štúrovo',
  'Svätuše',
  'Tlmače',
  'Topoľčany',
  'Tornaľa',
  'Trebišov',
  'Trenčianske Teplice',
  'Trstená',
  'Turčianske Teplice',
  'Turany',
  'Turzovka',
  'Tvrdošín',
  'Veľké Kapušany',
  'Veľký Krtíš',
  'Veľký Meder',
  'Veľký Šariš',
  'Vráble',
  'Vranov nad Topľou',
  'Vrbové',
  'Zlaté Moravce',
  'Zvolen',
  'Žarnovica',
  'Žiar nad Hronom',
]
