// Zoznam miest pre autocomplete trás
// name = zobrazovaný názov (slovenský), alt = originálny názov (pre vyhľadávanie)

export interface City {
  name: string
  alt?: string
}

// ZVL (sídlo firmy) ako prvá položka, potom SK krajské mestá, SK abecedne, potom zahraničné
export const CITIES: City[] = [
  // Sídlo firmy
  { name: 'ZVL' },
  // Krajské mestá
  { name: 'Bratislava' },
  { name: 'Košice' },
  { name: 'Prešov' },
  { name: 'Žilina' },
  { name: 'Banská Bystrica' },
  { name: 'Nitra' },
  { name: 'Trnava' },
  { name: 'Trenčín' },
  // Ostatné slovenské mestá abecedne
  { name: 'Bánovce nad Bebravou' },
  { name: 'Banská Štiavnica' },
  { name: 'Bardejov' },
  { name: 'Bojnice' },
  { name: 'Brezno' },
  { name: 'Brezová pod Bradlom' },
  { name: 'Bytča' },
  { name: 'Čadca' },
  { name: 'Detva' },
  { name: 'Dolný Kubín' },
  { name: 'Dubnica nad Váhom' },
  { name: 'Dunajská Streda' },
  { name: 'Fiľakovo' },
  { name: 'Galanta' },
  { name: 'Gelnica' },
  { name: 'Handlová' },
  { name: 'Hlohovec' },
  { name: 'Hnúšťa' },
  { name: 'Holíč' },
  { name: 'Humenné' },
  { name: 'Hurbanovo' },
  { name: 'Ilava' },
  { name: 'Jelšava' },
  { name: 'Kežmarok' },
  { name: 'Kolárovo' },
  { name: 'Komárno' },
  { name: 'Košice-okolie' },
  { name: 'Kremnica' },
  { name: 'Krupina' },
  { name: 'Kysucké Nové Mesto' },
  { name: 'Leopoldov' },
  { name: 'Levice' },
  { name: 'Levoča' },
  { name: 'Lipany' },
  { name: 'Liptovský Mikuláš' },
  { name: 'Lučenec' },
  { name: 'Malacky' },
  { name: 'Martin' },
  { name: 'Medzilaborce' },
  { name: 'Medzev' },
  { name: 'Michalovce' },
  { name: 'Modra' },
  { name: 'Moldava nad Bodvou' },
  { name: 'Modrý Kameň' },
  { name: 'Myjava' },
  { name: 'Námestovo' },
  { name: 'Nitra-okolie' },
  { name: 'Nová Baňa' },
  { name: 'Nová Dubnica' },
  { name: 'Nové Mesto nad Váhom' },
  { name: 'Nové Zámky' },
  { name: 'Partizánske' },
  { name: 'Pezinok' },
  { name: 'Piešťany' },
  { name: 'Podolínec' },
  { name: 'Poltár' },
  { name: 'Poprad' },
  { name: 'Považská Bystrica' },
  { name: 'Prievidza' },
  { name: 'Púchov' },
  { name: 'Revúca' },
  { name: 'Rimavská Sobota' },
  { name: 'Rožňava' },
  { name: 'Ružomberok' },
  { name: 'Sabinov' },
  { name: 'Šahy' },
  { name: 'Šaľa' },
  { name: 'Šamorín' },
  { name: 'Sečovce' },
  { name: 'Senec' },
  { name: 'Senica' },
  { name: 'Sereď' },
  { name: 'Skalica' },
  { name: 'Sládkovičovo' },
  { name: 'Snina' },
  { name: 'Sobrance' },
  { name: 'Spišská Belá' },
  { name: 'Spišská Nová Ves' },
  { name: 'Spišská Stará Ves' },
  { name: 'Spišské Podhradie' },
  { name: 'Spišské Vlachy' },
  { name: 'Stará Ľubovňa' },
  { name: 'Stará Turá' },
  { name: 'Stropkov' },
  { name: 'Stupava' },
  { name: 'Šurany' },
  { name: 'Svätý Jur' },
  { name: 'Svidník' },
  { name: 'Šaštín-Stráže' },
  { name: 'Štúrovo' },
  { name: 'Svätuše' },
  { name: 'Tlmače' },
  { name: 'Topoľčany' },
  { name: 'Tornaľa' },
  { name: 'Trebišov' },
  { name: 'Trenčianske Teplice' },
  { name: 'Trstená' },
  { name: 'Turčianske Teplice' },
  { name: 'Turany' },
  { name: 'Turzovka' },
  { name: 'Tvrdošín' },
  { name: 'Veľké Kapušany' },
  { name: 'Veľký Krtíš' },
  { name: 'Veľký Meder' },
  { name: 'Veľký Šariš' },
  { name: 'Vráble' },
  { name: 'Vranov nad Topľou' },
  { name: 'Vrbové' },
  { name: 'Zlaté Moravce' },
  { name: 'Zvolen' },
  { name: 'Žarnovica' },
  { name: 'Žiar nad Hronom' },
  // Česko
  { name: 'Praha' },
  { name: 'Brno' },
  { name: 'Ostrava' },
  { name: 'Plzeň' },
  { name: 'Liberec' },
  { name: 'Olomouc' },
  { name: 'České Budějovice' },
  { name: 'Hradec Králové' },
  { name: 'Ústí nad Labem' },
  { name: 'Pardubice' },
  { name: 'Zlín' },
  { name: 'Havířov' },
  { name: 'Kladno' },
  { name: 'Most' },
  { name: 'Opava' },
  { name: 'Frýdek-Místek' },
  { name: 'Karviná' },
  { name: 'Jihlava' },
  { name: 'Teplice' },
  { name: 'Děčín' },
  { name: 'Karlovy Vary' },
  { name: 'Chomutov' },
  { name: 'Jablonec nad Nisou' },
  { name: 'Prostějov' },
  { name: 'Přerov' },
  { name: 'Česká Lípa' },
  { name: 'Třebíč' },
  { name: 'Třinec' },
  { name: 'Tábor' },
  { name: 'Znojmo' },
  // Poľsko
  { name: 'Varšava', alt: 'Warszawa' },
  { name: 'Krakov', alt: 'Kraków' },
  { name: 'Vroclav', alt: 'Wrocław' },
  { name: 'Lodž', alt: 'Łódź' },
  { name: 'Poznaň', alt: 'Poznań' },
  { name: 'Gdansk', alt: 'Gdańsk' },
  { name: 'Štetín', alt: 'Szczecin' },
  { name: 'Katovice', alt: 'Katowice' },
  { name: 'Lublin' },
  { name: 'Bialystok', alt: 'Białystok' },
  { name: 'Gdyňa', alt: 'Gdynia' },
  { name: 'Čenstochová', alt: 'Częstochowa' },
  { name: 'Radom' },
  { name: 'Rzeszów' },
  { name: 'Toruň', alt: 'Toruń' },
  { name: 'Kielce' },
  { name: 'Sosnoviec', alt: 'Sosnowiec' },
  { name: 'Glivice', alt: 'Gliwice' },
  { name: 'Bielsko-Biała' },
  { name: 'Zabrze' },
  // Maďarsko
  { name: 'Budapešť', alt: 'Budapest' },
  { name: 'Debrecín', alt: 'Debrecen' },
  { name: 'Segedín', alt: 'Szeged' },
  { name: 'Miškolc', alt: 'Miskolc' },
  { name: 'Päťkostolie', alt: 'Pécs' },
  { name: 'Ráb', alt: 'Győr' },
  { name: 'Níreďháza', alt: 'Nyíregyháza' },
  { name: 'Kečkemét', alt: 'Kecskemét' },
  { name: 'Stoličný Belehrad', alt: 'Székesfehérvár' },
  { name: 'Szombathely' },
  { name: 'Szolnok' },
  { name: 'Tatabánya' },
  { name: 'Kaposvár' },
  { name: 'Érd' },
  { name: 'Veszprém' },
  { name: 'Békešská Čaba', alt: 'Békéscsaba' },
  { name: 'Zalaegerszeg' },
  { name: 'Šoproň', alt: 'Sopron' },
  { name: 'Jáger', alt: 'Eger' },
  { name: 'Nagykanizsa' },
  // Rakúsko
  { name: 'Viedeň', alt: 'Wien' },
  { name: 'Štajerský Hradec', alt: 'Graz' },
  { name: 'Linec', alt: 'Linz' },
  { name: 'Salzburg' },
  { name: 'Innsbruck' },
  { name: 'Klagenfurt' },
  { name: 'Villach' },
  { name: 'Wels' },
  { name: 'Svätý Hypolit', alt: 'Sankt Pölten' },
  { name: 'Dornbirn' },
  { name: 'Viedenské Nové Mesto', alt: 'Wiener Neustadt' },
  { name: 'Steyr' },
  { name: 'Feldkirch' },
  { name: 'Bregenz' },
  { name: 'Leonding' },
  { name: 'Baden' },
  { name: 'Wolfsberg' },
  { name: 'Leoben' },
  { name: 'Kremža', alt: 'Krems an der Donau' },
  { name: 'Eisenstadt' },
  // Nemecko
  { name: 'Berlín', alt: 'Berlin' },
  { name: 'Mníchov', alt: 'München' },
  { name: 'Hamburg' },
  { name: 'Frankfurt nad Mohanom', alt: 'Frankfurt am Main' },
  { name: 'Stuttgart' },
  { name: 'Düsseldorf' },
  { name: 'Kolín nad Rýnom', alt: 'Köln' },
  { name: 'Drážďany', alt: 'Dresden' },
  { name: 'Lipsko', alt: 'Leipzig' },
  { name: 'Norimberg', alt: 'Nürnberg' },
  { name: 'Hannover' },
  { name: 'Brémy', alt: 'Bremen' },
  { name: 'Dortmund' },
  { name: 'Essen' },
  { name: 'Regensburg' },
  { name: 'Pasov', alt: 'Passau' },
  { name: 'Augsburg' },
  { name: 'Mannheim' },
  { name: 'Karlsruhe' },
  { name: 'Saská Kamenica', alt: 'Chemnitz' },
]
